# Applied Finance with Python - Pandas Exercises
## Apple Stock Analysis (2021-2024)
## STUDENT VERSION

**Instructor:** Fatih Kuruscu

This notebook contains exercises to practice Pandas fundamentals using Apple (AAPL) stock data. Work through these exercises independently after the Microsoft example.

**Instructions:**
- Complete all tasks in order
- Write your code in the provided cells
- Test your code to ensure it runs without errors
- Points are indicated for each task
- Total points: 100 (plus 10 bonus points)

In [1]:
# Import libraries
import pandas as pd
import numpy as np

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 2)

print("Setup complete!")

Setup complete!

# Exercise 1: Data Loading and Exploration

## Task 1.1: Load the Data

Load the Apple stock data from `AAPL_2021_2024.csv` into a DataFrame called `df`.

Print the shape (number of rows and columns) of the dataset.

In [2]:
path_to_data = "../../data/AAPL_2021_2024.csv"
df = pd.read_csv(path_to_data)
df.shape

(1004, 8)

## Task 1.2: Initial Exploration

Display:
- The first 10 rows
- The last 5 rows
- A random sample of 8 rows

## Task 1.3: Data Structure

1. Display the DataFrame info using `.info()`
2. Print all column names
3. Check the data type of each column

## Task 1.4: Summary Statistics

Calculate and display:
1. Descriptive statistics for all numerical columns using `.describe()`
2. The mean, median, min, and max of the `Close` column
3. The total number of missing values in the entire DataFrame

np.int64(0)

## Task 1.5: Data Preparation

1. Convert the `Date` column to datetime format
2. Set the `Date` column as the index (save as `df_indexed`)
3. Display the first 5 rows of `df_indexed`

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], utc=True)
df_indexed = df.set_index('Date')
df_indexed.head()

# Exercise 2: Data Selection and Filtering

## Task 2.1: Column Selection

1. Select only the `Close` column and display the first 10 values
2. Select the columns `Open`, `High`, `Low`, and `Close` (OHLC data) and display the first 10 rows

## Task 2.2: Row Slicing

Using slicing notation, extract:
1. Rows 50 to 60
2. The last 20 rows
3. Every 100th row (show Date and Close columns only)

## Task 2.3: Boolean Filtering - Single Condition

Filter the data to find:
1. All days where the closing price was above $170
2. All days where the volume was greater than 100 million shares

For each filter, display:
- The number of days that meet the condition
- The percentage of total trading days
- The first 5 rows

In [38]:
#len

## Task 2.4: Boolean Filtering - Multiple Conditions

Find all days where:
1. Close price > $150 AND Volume > 80 million (use `&`)

2. Close price > $180 OR Volume > 120 million (use `|`)

3. Close price is between $140 and $160 (use `.between()`)

For each, display the count and first 5 rows.

## Task 2.5: iloc - Position-based Selection

Using `.iloc`, extract:
1. The value in row 100, column 4 (Close price)
2. Rows 200-210, all columns
3. All rows, columns 1-4 (Open through Close) - display first 10 rows

In [46]:
# df.iloc[100,4]
# df.iloc[200:211]

# Exercise 3: Data Transformations

## Task 3.1: Basic Calculations

Create a copy of the DataFrame called `df_work` and add the following columns:

1. `Daily_Range` = High - Low
2. `Range_Pct` = (Daily_Range / Open) * 100
3. `Intraday_Change` = Close - Open
4. `Intraday_Change_Pct` = (Intraday_Change / Open) * 100

Display the first 10 rows with Date, Open, High, Low, Close, and all new columns.

## Task 3.2: Returns Analysis

Calculate the following return metrics:

1. `Returns` = Daily simple returns using `.pct_change()`
2. `Returns_Pct` = Returns in percentage
3. `Cumulative_Returns` = Cumulative returns over the entire period

In [58]:
# Whats cumulative returns?

## Task 3.3: Moving Averages
Calculate the following moving averages on the Close price:

1. `SMA_10` = 10-day simple moving average
2. `SMA_30` = 30-day simple moving average
3. `SMA_50` = 50-day simple moving average

Then:
- Display the last 15 rows showing Date, Close, and all three SMAs
- Create a column `Above_SMA30` that shows 'Above' if Close > SMA_30, else 'Below'
- Count how many days the close was above vs below the 30-day SMA

## Task 3.4: Advanced Features 

Create the following features:

1. `Close_Lag1` = Previous day's close price (use `.shift(1)`)
2. `Close_Lag5` = Close price from 5 days ago
3. `Change_From_5Days_Ago` = Close - Close_Lag5
4. `Pct_Change_From_5Days_Ago` = Percentage change from 5 days ago

Display rows 10-20 with Date, Close, and all lag features.

In [ ]:
#explain why this is meaningful / sensible

# Exercise 4: Grouping and Aggregation

## Task 4.1: Date Feature Extraction

Extract the following from the Date column:
1. `Year`
2. `Month`
3. `Quarter`
4. `Day_of_Week` (0=Monday, 6=Sunday)

Display the first 15 rows with Date and all extracted features.

In [67]:
df_work['Year'] = df_work['Date'].dt.year
df_work['Month'] = df_work['Date'].dt.month
df_work['Quarter'] = df_work['Date'].dt.quarter
df_work['Day_of_Week'] = df_work['Date'].dt.dayofweek

## Task 4.2: Annual Analysis 

Group the data by Year and calculate:

1. Mean, Median, Min, and Max of the Close price for each year
2. Mean daily return for each year (in %)

Present your results in a well-formatted table.

## Task 4.3: Quarterly Performance

For each quarter in each year:
1. Calculate the mean closing price
2. Calculate the total return for that quarter
3. Identify which quarter had the best performance
4. Identify which quarter had the worst performance

Create a pivot table or grouped table showing Year x Quarter.

In [82]:
# SOLUTION
quarterly_stats = df_work.groupby(['Year', 'Quarter']).agg({
    'Close': 'mean',
    'Returns': lambda x: ((1 + x).prod() - 1) * 100
}).round(2)

quarterly_stats.columns = ['Mean_Close', 'Quarterly_Return_%']

print("Quarterly Statistics:")
display(quarterly_stats)

# Best and worst quarters
best_quarter = quarterly_stats['Quarterly_Return_%'].idxmax()
worst_quarter = quarterly_stats['Quarterly_Return_%'].idxmin()

print(f"\nBest quarter: {best_quarter} with {quarterly_stats.loc[best_quarter, 'Quarterly_Return_%']:.2f}% return")
print(f"Worst quarter: {worst_quarter} with {quarterly_stats.loc[worst_quarter, 'Quarterly_Return_%']:.2f}% return")

Quarterly Statistics:

              Mean_Close  Quarterly_Return_%
Year Quarter
2021 1            125.19               -5.47
     2            126.57               12.31
     3            144.04                3.47
     4            154.86               25.67
2022 1            165.00               -1.54
     2            148.79              -21.58
     3            154.43                1.22
     4            140.83               -5.83
2023 1            145.63               27.11
     2            172.22               17.79
     3            181.49              -11.61
     4            182.98               12.60
2024 1            180.43              -10.82
     2            185.30               22.99
     3            222.17               10.75
     4            234.50                8.36

Best quarter: (np.int32(2023), np.int32(1)) with 27.11% return
Worst quarter: (np.int32(2022), np.int32(2)) with -21.58% return

## Task 4.4: Day of Week Analysis 

Analyze returns by day of the week:
1. Calculate mean return for each day of the week
2. Calculate the percentage of positive return days for each weekday
3. Determine which day of the week had the highest average return
4. Determine which day had the most volatile returns (highest std)

Present the results in a clear table.

In [83]:
# SOLUTION
# Create day names
day_names = {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday'}
df_work['Day_Name'] = df_work['Day_of_Week'].map(day_names)

# Calculate statistics by day
day_stats = df_work.groupby('Day_Name')['Returns'].agg([
    ('Mean_Return_%', lambda x: x.mean() * 100),
    ('Std_Return_%', lambda x: x.std() * 100),
    ('Positive_Days_%', lambda x: (x > 0).sum() / len(x) * 100),
    ('Count', 'count')
]).round(3)

# Reorder by day of week
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
day_stats = day_stats.reindex(day_order)

print("Day of Week Analysis:")
display(day_stats)

# Best and worst days
best_day = day_stats['Mean_Return_%'].idxmax()
most_volatile_day = day_stats['Std_Return_%'].idxmax()

print(f"\nBest day: {best_day} with average return of {day_stats.loc[best_day, 'Mean_Return_%']:.3f}%")
print(f"Most volatile day: {most_volatile_day} with std of {day_stats.loc[most_volatile_day, 'Std_Return_%']:.3f}%")

Day of Week Analysis:

           Mean_Return_%  Std_Return_%  Positive_Days_%  Count
Day_Name
Monday          1.45e-01          1.64            56.22    184
Tuesday         9.80e-02          1.55            54.59    207
Wednesday       6.00e-03          1.57            50.48    206
Thursday        2.60e-02          1.88            51.23    203
Friday          1.45e-01          1.73            53.70    203

Best day: Monday with average return of 0.145%
Most volatile day: Thursday with std of 1.879%

In [92]:
df_work[['Year','Quarter', 'Close']].groupby(['Year','Quarter']).agg(
    max_close=('Close', 'max'),
    avg_close=('Close', 'mean')
)

              max_close  avg_close
Year Quarter
2021 1           139.49     125.19
     2           133.88     126.57
     3           153.40     144.04
     4           176.80     154.86
2022 1           178.44     165.00
     2           175.17     148.79
     3           171.84     154.43
     4           153.32     140.83
2023 1           162.86     145.63
     2           191.83     172.22
     3           194.28     181.49
     4           196.45     182.98
2024 1           193.54     180.43
     2           215.42     185.30
     3           233.46     222.17
     4           258.10     234.50

In [89]:
df_work[['Year','Quarter', 'Close']].groupby(['Year','Quarter']).mean()

               Close
Year Quarter
2021 1        125.19
     2        126.57
     3        144.04
     4        154.86
2022 1        165.00
     2        148.79
     3        154.43
     4        140.83
2023 1        145.63
     2        172.22
     3        181.49
     4        182.98
2024 1        180.43
     2        185.30
     3        222.17
     4        234.50