# Applied Finance with Python - Pandas Fundamentals
## Microsoft Stock Analysis (2021-2024)

**Instructor:** Fatih Kuruscu

In this notebook, we will explore fundamental Pandas operations using real financial data from Microsoft (MSFT) stock.

# 1. Setup and Data Import

In [15]:
# Import required libraries
import pandas as pd
import numpy as np

# Set display options for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 2)

# 2. Loading the Data

In [19]:
path_to_data = "../../data/MSFT_2021_2024.csv"
df = pd.read_csv(path_to_data)

print("Data loaded successfully!")
print(f"\nDataset shape: {df.shape}")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Data loaded successfully!

Dataset shape: (1004, 8)
Number of rows: 1004
Number of columns: 8

# 3. Data Exploration

## 3.1 First Look at the Data

In [20]:
# Display first 5 rows
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,143301900,0.0,0.0
1,2021-01-05 00:00:00-05:00,125.59,128.37,125.14,127.66,97664900,0.0,0.0
2,2021-01-06 00:00:00-05:00,124.45,127.69,123.14,123.36,155088000,0.0,0.0
3,2021-01-07 00:00:00-05:00,125.07,128.26,124.59,127.57,109578200,0.0,0.0
4,2021-01-08 00:00:00-05:00,129.04,129.23,126.90,128.67,105158200,0.0,0.0

In [21]:
# Display last 5 rows
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
999,2024-12-23 00:00:00-05:00,253.87,254.75,252.55,254.37,40858800,0.0,0.0
1000,2024-12-24 00:00:00-05:00,254.59,257.30,254.39,257.29,23234700,0.0,0.0
1001,2024-12-26 00:00:00-05:00,257.28,259.18,256.72,258.10,27237100,0.0,0.0
1002,2024-12-27 00:00:00-05:00,256.92,257.78,252.16,254.69,42355300,0.0,0.0
1003,2024-12-30 00:00:00-05:00,251.34,252.60,249.86,251.31,35557500,0.0,0.0

In [22]:
# Display random 10 rows
df.sample(10)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
423,2022-09-08 00:00:00-04:00,152.24,153.93,150.31,152.06,84923800,0.0,0.0
384,2022-07-14 00:00:00-04:00,141.64,146.43,140.83,145.96,78140700,0.0,0.0
676,2023-09-12 00:00:00-04:00,177.75,178.38,173.12,174.59,90370200,0.0,0.0
905,2024-08-09 00:00:00-04:00,210.87,215.53,210.74,214.99,42201600,0.0,0.0
429,2022-09-16 00:00:00-04:00,148.86,149.00,146.06,148.36,162278800,0.0,0.0
341,2022-05-11 00:00:00-04:00,150.90,152.82,143.34,144.02,142689800,0.0,0.0
637,2023-07-18 00:00:00-04:00,191.22,192.19,190.30,191.59,48288200,0.0,0.0
100,2021-05-27 00:00:00-04:00,123.60,124.77,122.27,122.46,94625600,0.0,0.0
256,2022-01-07 00:00:00-05:00,169.50,170.73,167.68,168.80,86709100,0.0,0.0
191,2021-10-06 00:00:00-04:00,136.54,139.16,135.46,139.01,83221100,0.0,0.0

## 3.2 Data Structure and Types

In [23]:
# Get information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1004 non-null   datetime64[ns, America/New_York]
 1   Open          1004 non-null   float64
 2   High          1004 non-null   float64
 3   Low           1004 non-null   float64
 4   Close         1004 non-null   float64
 5   Volume        1004 non-null   int64
 6   Dividends     1004 non-null   float64
 7   Stock Splits  1004 non-null   float64
dtypes: datetime64[ns, America/New_York](1), float64(6), int64(1)
memory usage: 62.9 KB

In [24]:
# Display column names
print("Column names:")
print(df.columns.tolist())

Column names:
['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits']

In [25]:
# Display data types
print("Data types:")
df.dtypes

Data types:

Date            datetime64[ns, America/New_York]
Open                                     float64
High                                     float64
Low                                      float64
Close                                    float64
Volume                                     int64
Dividends                                float64
Stock Splits                             float64
dtype: object

## 3.3 Summary Statistics

In [26]:
# Descriptive statistics for numerical columns
df.describe()

          Open     High      Low    Close    Volume  Dividends  Stock Splits
count  1004.00  1004.00  1004.00  1004.00  1.00e+03   1.00e+03        1004.0
mean    166.45   168.21   164.85   166.63  7.37e+07   3.70e-03           0.0
std      31.21    31.33    31.14    31.29  3.02e+07   2.91e-02           0.0
min     116.16   117.49   113.40   113.55  2.32e+07   0.00e+00           0.0
25%     142.97   144.80   141.61   143.15  5.22e+07   0.00e+00           0.0
50%     163.91   165.78   162.36   163.54  6.80e+07   0.00e+00           0.0
75%     183.48   184.94   181.91   183.34  8.86e+07   0.00e+00           0.0
max     257.28   259.18   256.72   258.10  3.19e+08   2.50e-01           0.0

In [27]:
# Additional statistics
print("Additional Statistics:")
print(f"\nMean Close Price: ${df['Close'].mean():.2f}")
print(f"Median Close Price: ${df['Close'].median():.2f}")
print(f"Standard Deviation: ${df['Close'].std():.2f}")
print(f"Min Close Price: ${df['Close'].min():.2f}")
print(f"Max Close Price: ${df['Close'].max():.2f}")

Additional Statistics:

Mean Close Price: $166.63
Median Close Price: $163.54
Standard Deviation: $31.29
Min Close Price: $113.55
Max Close Price: $258.10

## 3.4 Missing Values

In [28]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())
print(f"\nTotal missing values: {df.isnull().sum().sum()}")
print(f"Percentage of missing data: {(df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100):.2f}%")

Missing values per column:
Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

Total missing values: 0
Percentage of missing data: 0.00%

# 5. Selecting Data - Columns

## 5.1 Single Column Selection

In [29]:
# Select a single column - returns a Series
close_prices = df['Close']

print(f"Type: {type(close_prices)}")
print(f"\nFirst 5 values:")
print(close_prices.head())

Type: <class 'pandas.core.series.Series'>

First 5 values:
0    126.10
1    127.66
2    123.36
3    127.57
4    128.67
Name: Close, dtype: float64

In [30]:
# Alternative syntax using dot notation (only works for column names without spaces)
close_prices_alt = df.Close
print(close_prices_alt.head())

0    126.10
1    127.66
2    123.36
3    127.57
4    128.67
Name: Close, dtype: float64

## 5.2 Multiple Column Selection

In [32]:
# Select multiple columns - returns a DataFrame
price_data = df[['Open', 'High', 'Low', 'Close']]

print(f"Type: {type(price_data)}")
print(f"Shape: {price_data.shape}")
print("\nFirst 5 rows:")
print(price_data.head())

Type: <class 'pandas.core.frame.DataFrame'>
Shape: (1004, 4)

First 5 rows:
     Open    High     Low   Close
0  130.10  130.19  123.51  126.10
1  125.59  128.37  125.14  127.66
2  124.45  127.69  123.14  123.36
3  125.07  128.26  124.59  127.57
4  129.04  129.23  126.90  128.67

In [33]:
# Select specific columns for analysis
df[['Date', 'Close', 'Volume']].head(10)

                       Date   Close     Volume
0 2021-01-04 00:00:00-05:00  126.10  143301900
1 2021-01-05 00:00:00-05:00  127.66   97664900
2 2021-01-06 00:00:00-05:00  123.36  155088000
3 2021-01-07 00:00:00-05:00  127.57  109578200
4 2021-01-08 00:00:00-05:00  128.67  105158200
5 2021-01-11 00:00:00-05:00  125.68  100384500
6 2021-01-12 00:00:00-05:00  125.50   91951100
7 2021-01-13 00:00:00-05:00  127.54   88636800
8 2021-01-14 00:00:00-05:00  125.61   90221800
9 2021-01-15 00:00:00-05:00  123.88  111598500

# 6. Selecting Data - Rows (Slicing)

## 6.1 Basic Row Slicing

In [35]:
# First 10 rows
print("First 10 rows:")
df[:10]

First 10 rows:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,143301900,0.0,0.0
1,2021-01-05 00:00:00-05:00,125.59,128.37,125.14,127.66,97664900,0.0,0.0
2,2021-01-06 00:00:00-05:00,124.45,127.69,123.14,123.36,155088000,0.0,0.0
3,2021-01-07 00:00:00-05:00,125.07,128.26,124.59,127.57,109578200,0.0,0.0
4,2021-01-08 00:00:00-05:00,129.04,129.23,126.90,128.67,105158200,0.0,0.0
5,2021-01-11 00:00:00-05:00,125.88,126.84,125.21,125.68,100384500,0.0,0.0
6,2021-01-12 00:00:00-05:00,125.21,126.37,123.61,125.50,91951100,0.0,0.0
7,2021-01-13 00:00:00-05:00,125.46,128.08,125.20,127.54,88636800,0.0,0.0
8,2021-01-14 00:00:00-05:00,127.45,127.65,125.46,125.61,90221800,0.0,0.0
9,2021-01-15 00:00:00-05:00,125.48,126.89,123.75,123.88,111598500,0.0,0.0

In [36]:
# Last 10 rows
print("Last 10 rows:")
df[-10:]

Last 10 rows:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
994,2024-12-16 00:00:00-05:00,247.11,250.49,246.77,250.15,51694800,0.0,0.0
995,2024-12-17 00:00:00-05:00,249.20,252.93,248.90,252.58,51356400,0.0,0.0
996,2024-12-18 00:00:00-05:00,251.27,253.38,246.86,247.17,56774100,0.0,0.0
997,2024-12-19 00:00:00-05:00,246.62,251.11,246.22,248.91,60882300,0.0,0.0
998,2024-12-20 00:00:00-05:00,247.16,254.10,244.82,253.59,147495300,0.0,0.0
999,2024-12-23 00:00:00-05:00,253.87,254.75,252.55,254.37,40858800,0.0,0.0
1000,2024-12-24 00:00:00-05:00,254.59,257.30,254.39,257.29,23234700,0.0,0.0
1001,2024-12-26 00:00:00-05:00,257.28,259.18,256.72,258.10,27237100,0.0,0.0
1002,2024-12-27 00:00:00-05:00,256.92,257.78,252.16,254.69,42355300,0.0,0.0
1003,2024-12-30 00:00:00-05:00,251.34,252.60,249.86,251.31,35557500,0.0,0.0

In [37]:
# Rows 100 to 110
print("Rows 100-110:")
df[100:110]

Rows 100-110:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
100,2021-05-27 00:00:00-04:00,123.60,124.77,122.27,122.46,94625600,0.0,0.0
101,2021-05-28 00:00:00-04:00,122.75,122.97,121.75,121.81,71311100,0.0,0.0
102,2021-06-01 00:00:00-04:00,122.27,122.53,121.15,121.48,67637100,0.0,0.0
103,2021-06-02 00:00:00-04:00,121.48,122.42,121.26,122.25,59278900,0.0,0.0
104,2021-06-03 00:00:00-04:00,121.88,122.04,120.36,120.76,76229200,0.0,0.0
105,2021-06-04 00:00:00-04:00,121.28,123.32,121.06,123.06,75169300,0.0,0.0
106,2021-06-07 00:00:00-04:00,123.33,123.48,122.02,123.07,71057600,0.0,0.0
107,2021-06-08 00:00:00-04:00,123.75,125.57,123.37,123.89,74403800,0.0,0.0
108,2021-06-09 00:00:00-04:00,124.35,124.88,123.67,124.27,56877900,0.0,0.0
109,2021-06-10 00:00:00-04:00,124.16,125.31,123.11,123.27,71186400,0.0,0.0

In [38]:
# Every 50th row
print("Every 50th row:")
df[::50]

Every 50th row:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,143301900,0.00,0.0
50,2021-03-17 00:00:00-04:00,121.05,122.82,119.39,121.75,111932600,0.00,0.0
100,2021-05-27 00:00:00-04:00,123.60,124.77,122.27,122.46,94625600,0.00,0.0
150,2021-08-09 00:00:00-04:00,143.13,143.62,142.46,143.02,48908700,0.00,0.0
200,2021-10-19 00:00:00-04:00,143.92,146.03,143.47,145.63,76378900,0.00,0.0
250,2021-12-30 00:00:00-05:00,175.95,177.03,174.60,174.71,59773000,0.00,0.0
300,2022-03-14 00:00:00-04:00,148.67,151.29,147.35,147.86,108732100,0.00,0.0
350,2022-05-24 00:00:00-04:00,138.43,139.57,135.01,137.99,104132700,0.00,0.0
400,2022-08-05 00:00:00-04:00,160.67,163.27,160.47,162.78,56697000,0.23,0.0
450,2022-10-17 00:00:00-04:00,138.88,140.68,138.09,140.20,85250900,0.00,0.0
500,2022-12-28 00:00:00-05:00,127.87,129.21,124.12,124.29,85438400,0.00,0.0
550,2023-03-13 00:00:00-04:00,145.98,151.24,145.87,148.60,84457100,0.00,0.0
600,2023-05-23 00:00:00-04:00,171.22,171.47,169.39,169.67,50747300,0.00,0.0
650,2023-08-04 00:00:00-04:00,183.47,185.31,179.91,179.98,115956800,0.00,0.0
700,2023-10-16 00:00:00-04:00,175.04,177.34,174.80,176.99,52517000,0.00,0.0
750,2023-12-27 00:00:00-05:00,190.87,191.88,189.49,191.53,48087700,0.00,0.0
800,2024-03-11 00:00:00-04:00,171.71,173.14,170.82,171.52,60139500,0.00,0.0
850,2024-05-21 00:00:00-04:00,189.98,191.62,189.82,191.24,42309400,0.00,0.0
900,2024-08-02 00:00:00-04:00,217.88,224.30,216.45,218.59,105568600,0.00,0.0
950,2024-10-14 00:00:00-04:00,227.64,230.66,227.54,230.23,39882100,0.00,0.0
1000,2024-12-24 00:00:00-05:00,254.59,257.30,254.39,257.29,23234700,0.00,0.0

## 6.2 Conditional Selection (Boolean Indexing)

In [39]:
# Days where closing price was above $300
high_price_days = df[df['Close'] > 300]

print(f"Number of days with Close > $300: {len(high_price_days)}")
print(f"Percentage of total days: {len(high_price_days) / len(df) * 100:.2f}%")
print("\nFirst few high-price days:")
high_price_days.head()

Number of days with Close > $300: 0
Percentage of total days: 0.00%

First few high-price days:

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

In [40]:
# Days with high volume (above 30 million)
high_volume_days = df[df['Volume'] > 30000000]

print(f"Number of high-volume days: {len(high_volume_days)}")
high_volume_days.head()

Number of high-volume days: 997

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,143301900,0.0,0.0
1,2021-01-05 00:00:00-05:00,125.59,128.37,125.14,127.66,97664900,0.0,0.0
2,2021-01-06 00:00:00-05:00,124.45,127.69,123.14,123.36,155088000,0.0,0.0
3,2021-01-07 00:00:00-05:00,125.07,128.26,124.59,127.57,109578200,0.0,0.0
4,2021-01-08 00:00:00-05:00,129.04,129.23,126.90,128.67,105158200,0.0,0.0

In [41]:
# Multiple conditions with & (AND)
# Days where Close > $300 AND Volume > 30 million
condition = (df['Close'] > 300) & (df['Volume'] > 30000000)
filtered_df = df[condition]

print(f"Days with Close > $300 AND Volume > 30M: {len(filtered_df)}")
filtered_df.head()

Days with Close > $300 AND Volume > 30M: 0

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

In [42]:
# Multiple conditions with | (OR)
# Days where Close > $350 OR Volume > 50 million
condition = (df['Close'] > 350) | (df['Volume'] > 50000000)
filtered_df = df[condition]

print(f"Days with Close > $350 OR Volume > 50M: {len(filtered_df)}")
filtered_df.head()

Days with Close > $350 OR Volume > 50M: 790

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,143301900,0.0,0.0
1,2021-01-05 00:00:00-05:00,125.59,128.37,125.14,127.66,97664900,0.0,0.0
2,2021-01-06 00:00:00-05:00,124.45,127.69,123.14,123.36,155088000,0.0,0.0
3,2021-01-07 00:00:00-05:00,125.07,128.26,124.59,127.57,109578200,0.0,0.0
4,2021-01-08 00:00:00-05:00,129.04,129.23,126.90,128.67,105158200,0.0,0.0

In [43]:
# Using .between() for range selection
# Days where closing price was between $250 and $300
mid_range_days = df[df['Close'].between(250, 300)]

print(f"Days with Close between $250-$300: {len(mid_range_days)}")
mid_range_days.head()

Days with Close between $250-$300: 8

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
994,2024-12-16 00:00:00-05:00,247.11,250.49,246.77,250.15,51694800,0.0,0.0
995,2024-12-17 00:00:00-05:00,249.20,252.93,248.90,252.58,51356400,0.0,0.0
998,2024-12-20 00:00:00-05:00,247.16,254.10,244.82,253.59,147495300,0.0,0.0
999,2024-12-23 00:00:00-05:00,253.87,254.75,252.55,254.37,40858800,0.0,0.0
1000,2024-12-24 00:00:00-05:00,254.59,257.30,254.39,257.29,23234700,0.0,0.0

# 7. Indexing with iloc

In [44]:
# Select single row by position (row 0)
print("First row using iloc:")
df.iloc[0]

First row using iloc:

Date            2021-01-04 00:00:00-05:00
Open                                130.1
High                               130.19
Low                                123.51
Close                               126.1
Volume                          143301900
Dividends                             0.0
Stock Splits                          0.0
Name: 0, dtype: object

In [45]:
# Select single cell by position (row 0, column 4 = Close)
print("First closing price:")
first_close = df.iloc[0, 4]
print(f"${first_close:.2f}")

First closing price:
$126.10

In [46]:
# Select multiple rows by position
print("Rows 0-4 using iloc:")
df.iloc[0:5]

Rows 0-4 using iloc:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,143301900,0.0,0.0
1,2021-01-05 00:00:00-05:00,125.59,128.37,125.14,127.66,97664900,0.0,0.0
2,2021-01-06 00:00:00-05:00,124.45,127.69,123.14,123.36,155088000,0.0,0.0
3,2021-01-07 00:00:00-05:00,125.07,128.26,124.59,127.57,109578200,0.0,0.0
4,2021-01-08 00:00:00-05:00,129.04,129.23,126.90,128.67,105158200,0.0,0.0

In [47]:
# Select specific rows and columns
# Rows 0-9, columns 0 (Date) and 4 (Close)
print("First 10 dates and closing prices:")
df.iloc[0:10, [0, 4]]

First 10 dates and closing prices:

                       Date   Close
0 2021-01-04 00:00:00-05:00  126.10
1 2021-01-05 00:00:00-05:00  127.66
2 2021-01-06 00:00:00-05:00  123.36
3 2021-01-07 00:00:00-05:00  127.57
4 2021-01-08 00:00:00-05:00  128.67
5 2021-01-11 00:00:00-05:00  125.68
6 2021-01-12 00:00:00-05:00  125.50
7 2021-01-13 00:00:00-05:00  127.54
8 2021-01-14 00:00:00-05:00  125.61
9 2021-01-15 00:00:00-05:00  123.88

In [48]:
# Select all rows, specific columns
# All rows, columns 1-4 (Open, High, Low, Close)
print("All OHLC data:")
df.iloc[:, 1:5].head()

All OHLC data:

     Open    High     Low   Close
0  130.10  130.19  123.51  126.10
1  125.59  128.37  125.14  127.66
2  124.45  127.69  123.14  123.36
3  125.07  128.26  124.59  127.57
4  129.04  129.23  126.90  128.67

In [50]:
# Select last row
print("Last trading day:")
df.iloc[-1]

Last trading day:

Date            2024-12-30 00:00:00-05:00
Open                               251.34
High                                252.6
Low                                249.86
Close                              251.31
Volume                           35557500
Dividends                             0.0
Stock Splits                          0.0
Name: 1003, dtype: object

# 8. Data Transformations - Create new Columns

In [53]:
# Create a copy to work with
df_transform = df.copy()

# Daily price range
df_transform['Daily_Range'] = df_transform['High'] - df_transform['Low']

# Daily range as percentage
df_transform['Range_Pct'] = (df_transform['Daily_Range'] / df_transform['Open']) * 100

# Price change from open to close
df_transform['Price_Change'] = df_transform['Close'] - df_transform['Open']

print("New columns created:")
df_transform[['Date', 'Open', 'High', 'Low', 'Close', 'Daily_Range', 'Range_Pct', 'Price_Change']].head(10)

New columns created:

,Date,Open,High,Low,Close,Daily_Range,Range_Pct,Price_Change
0,2021-01-04 00:00:00-05:00,130.10,130.19,123.51,126.10,6.67,5.13,-4.00
1,2021-01-05 00:00:00-05:00,125.59,128.37,125.14,127.66,3.23,2.57,2.07
2,2021-01-06 00:00:00-05:00,124.45,127.69,123.14,123.36,4.55,3.66,-1.09
3,2021-01-07 00:00:00-05:00,125.07,128.26,124.59,127.57,3.67,2.94,2.49
4,2021-01-08 00:00:00-05:00,129.04,129.23,126.90,128.67,2.34,1.81,-0.37
5,2021-01-11 00:00:00-05:00,125.88,126.84,125.21,125.68,1.63,1.29,-0.20
6,2021-01-12 00:00:00-05:00,125.21,126.37,123.61,125.50,2.76,2.20,0.29
7,2021-01-13 00:00:00-05:00,125.46,128.08,125.20,127.54,2.88,2.30,2.08
8,2021-01-14 00:00:00-05:00,127.45,127.65,125.46,125.61,2.18,1.71,-1.84
9,2021-01-15 00:00:00-05:00,125.48,126.89,123.75,123.88,3.14,2.50,-1.60

# 9. Grouping and Aggregation - Group By Year

In [57]:
# Annual statistics
df_transform['Year'] = df_transform['Date'].dt.year

yearly_stats = df_transform.groupby('Year')['Close'].agg([
    ('Mean', 'mean'),
    ('Median', 'median'),
    ('Min', 'min'),
    ('Max', 'max'),
    ('Std', 'std')
]).round(2)

print("Yearly statistics for closing prices:")
yearly_stats

Yearly statistics for closing prices:

        Mean  Median     Min     Max    Std
Year
2021  137.86  138.28  113.55  176.80  14.55
2022  152.23  151.49  124.29  178.44  12.67
2023  170.68  173.77  123.28  196.45  17.36
2024  205.87  213.00  163.82  258.10  25.53