# Applied Finance with Python - Pandas Fundamentals
## Microsoft Stock Analysis (2021-2024)

**Instructor:** Fatih Kuruscu

In this notebook, we will explore fundamental Pandas operations using real financial data from Microsoft (MSFT) stock.

# 1. Setup and Data Import

In [8]:
# Import required libraries
import pandas as pd
import numpy as np

# Set display options for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 2)

# 2. Loading the Data

In [9]:
path_to_data = "../../data/MSFT_2021_2024.csv"
df = pd.read_csv(path_to_data)

print("Data loaded successfully!")
print(f"\nDataset shape: {df.shape}")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Data loaded successfully!

Dataset shape: (1004, 8)
Number of rows: 1004
Number of columns: 8

In [14]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1004 non-null   object
 1   Open          1004 non-null   float64
 2   High          1004 non-null   float64
 3   Low           1004 non-null   float64
 4   Close         1004 non-null   float64
 5   Volume        1004 non-null   int64
 6   Dividends     1004 non-null   float64
 7   Stock Splits  1004 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 62.9+ KB

In [6]:
type(df)

pandas.core.frame.DataFrame

# 3. Data Exploration

## 3.1 First Look at the Data

In [15]:
# Display first 5 rows
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0

In [16]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
999,2024-12-23 00:00:00-05:00,434.35,435.26,430.46,432.87,19152500,0.0,0.0
1000,2024-12-24 00:00:00-05:00,432.27,437.20,431.82,436.93,7164500,0.0,0.0
1001,2024-12-26 00:00:00-05:00,436.68,438.53,434.24,435.72,8194200,0.0,0.0
1002,2024-12-27 00:00:00-05:00,432.22,432.84,424.02,428.18,18117700,0.0,0.0
1003,2024-12-30 00:00:00-05:00,423.73,425.21,419.59,422.51,13158700,0.0,0.0

In [17]:
# Display random 10 rows
df.sample(10)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
179,2021-09-20 00:00:00-04:00,286.74,289.05,280.15,284.77,38278700,0.0,0.0
12,2021-01-21 00:00:00-05:00,216.01,217.55,213.82,216.27,30709400,0.0,0.0
981,2024-11-26 00:00:00-05:00,417.30,426.70,416.56,425.65,23458900,0.0,0.0
209,2021-11-01 00:00:00-04:00,320.63,320.76,315.80,318.71,27073200,0.0,0.0
369,2022-06-22 00:00:00-04:00,245.26,250.40,243.78,246.46,25939900,0.0,0.0
541,2023-02-28 00:00:00-05:00,244.32,246.69,243.99,244.66,22491000,0.0,0.0
80,2021-04-29 00:00:00-04:00,246.15,246.77,239.92,243.31,40589000,0.0,0.0
419,2022-09-01 00:00:00-04:00,252.59,254.56,249.21,254.08,23263400,0.0,0.0
653,2023-08-09 00:00:00-04:00,320.94,321.57,315.62,316.78,22373300,0.0,0.0
649,2023-08-03 00:00:00-04:00,320.48,324.30,320.43,321.13,18253700,0.0,0.0

## 3.2 Data Structure and Types

In [13]:
# Get information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1004 non-null   object
 1   Open          1004 non-null   float64
 2   High          1004 non-null   float64
 3   Low           1004 non-null   float64
 4   Close         1004 non-null   float64
 5   Volume        1004 non-null   int64
 6   Dividends     1004 non-null   float64
 7   Stock Splits  1004 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 62.9+ KB

In [14]:
# Display column names
print("Column names:")
print(df.columns.tolist())

Column names:
['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits']

In [17]:
# Display data types
print("Data types:")
df.dtypes

Data types:

Date             object
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends       float64
Stock Splits    float64
dtype: object

## 3.3 Summary Statistics

In [21]:
# Descriptive statistics for numerical columns
df.describe()

          Open     High      Low    Close    Volume  Dividends  Stock Splits
count  1004.00  1004.00  1004.00  1004.00  1.00e+03    1004.00        1004.0
mean    313.26   316.21   310.17   313.33  2.64e+07       0.01           0.0
std      69.78    69.93    69.40    69.71  1.03e+07       0.08           0.0
min     203.97   206.22   203.75   204.04  7.16e+06       0.00           0.0
25%     251.58   254.54   248.45   252.00  1.96e+07       0.00           0.0
50%     294.85   299.05   291.73   295.12  2.41e+07       0.00           0.0
75%     371.63   373.48   369.55   372.58  3.02e+07       0.00           0.0
max     462.69   464.02   460.17   463.24  9.04e+07       0.83           0.0

In [20]:
df['High'].max()

np.float64(464.0237082994549)

In [22]:
# Additional statistics
print("Additional Statistics:")
print(f"\nMean Close Price: ${df['Close'].mean():.2f}")
print(f"Median Close Price: ${df['Close'].median():.2f}")
print(f"Standard Deviation: ${df['Close'].std():.2f}")
print(f"Min Close Price: ${df['Close'].min():.2f}")
print(f"Max Close Price: ${df['Close'].max():.2f}")

Additional Statistics:

Mean Close Price: $313.33
Median Close Price: $295.12
Standard Deviation: $69.71
Min Close Price: $204.04
Max Close Price: $463.24

## 3.4 Missing Values

In [22]:
df.isnull().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [23]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())
print(f"\nTotal missing values: {df.isnull().sum().sum()}")
print(f"Percentage of missing data: {(df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100):.2f}%")

Missing values per column:
Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

Total missing values: 0
Percentage of missing data: 0.00%

# 5. Selecting Data - Columns

## 5.1 Single Column Selection

In [24]:
# Select a single column - returns a Series
close_prices = df['Close']

print(f"Type: {type(close_prices)}")
print(f"\nFirst 5 values:")
print(close_prices.head())

Type: <class 'pandas.core.series.Series'>

First 5 values:
0    209.27
1    209.48
2    204.04
3    209.85
4    211.13
Name: Close, dtype: float64

In [22]:
# Alternative syntax using dot notation (only works for column names without spaces)
close_prices_alt = df.Close
print(close_prices_alt.head())

0    209.27
1    209.48
2    204.04
3    209.85
4    211.13
Name: Close, dtype: float64

## 5.2 Multiple Column Selection

In [29]:
type(df)

pandas.core.frame.DataFrame

In [28]:
type(df['Low'])

pandas.core.series.Series

In [26]:
df[['Date','Low','High']]

                           Date     Low    High
0     2021-01-04 00:00:00-05:00  206.50  214.38
1     2021-01-05 00:00:00-05:00  207.36  210.07
2     2021-01-06 00:00:00-05:00  203.75  208.12
3     2021-01-07 00:00:00-05:00  205.45  210.86
4     2021-01-08 00:00:00-05:00  208.64  212.05
...                         ...     ...     ...
999   2024-12-23 00:00:00-05:00  430.46  435.26
1000  2024-12-24 00:00:00-05:00  431.82  437.20
1001  2024-12-26 00:00:00-05:00  434.24  438.53
1002  2024-12-27 00:00:00-05:00  424.02  432.84
1003  2024-12-30 00:00:00-05:00  419.59  425.21

[1004 rows x 3 columns]

In [25]:
# Select multiple columns - returns a DataFrame
price_data = df[['Open', 'High', 'Low', 'Close']]

print(f"Type: {type(price_data)}")
print(f"Shape: {price_data.shape}")
print("\nFirst 5 rows:")
print(price_data.head())

Type: <class 'pandas.core.frame.DataFrame'>
Shape: (1004, 4)

First 5 rows:
     Open    High     Low   Close
0  213.93  214.38  206.50  209.27
1  208.86  210.07  207.36  209.48
2  203.97  208.12  203.75  204.04
3  205.76  210.86  205.45  209.85
4  210.22  212.05  208.64  211.13

In [26]:
# Select specific columns for analysis
df[['Date', 'Close', 'Volume']].head(10)

                        Date   Close    Volume
0  2021-01-04 00:00:00-05:00  209.27  37130100
1  2021-01-05 00:00:00-05:00  209.48  23823000
2  2021-01-06 00:00:00-05:00  204.04  35930700
3  2021-01-07 00:00:00-05:00  209.85  27694500
4  2021-01-08 00:00:00-05:00  211.13  22956200
5  2021-01-11 00:00:00-05:00  209.08  23031300
6  2021-01-12 00:00:00-05:00  206.62  23249300
7  2021-01-13 00:00:00-05:00  207.98  20087100
8  2021-01-14 00:00:00-05:00  204.78  29480800
9  2021-01-15 00:00:00-05:00  204.43  31746500

# 6. Selecting Data - Rows (Slicing)

## 6.1 Basic Row Slicing

In [30]:
df[:10]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0
5,2021-01-11 00:00:00-05:00,210.02,210.45,208.35,209.08,23031300,0.0,0.0
6,2021-01-12 00:00:00-05:00,208.13,208.71,205.07,206.62,23249300,0.0,0.0
7,2021-01-13 00:00:00-05:00,205.75,208.38,205.66,207.98,20087100,0.0,0.0
8,2021-01-14 00:00:00-05:00,207.56,209.05,204.51,204.78,29480800,0.0,0.0
9,2021-01-15 00:00:00-05:00,205.26,206.22,203.83,204.43,31746500,0.0,0.0

In [27]:
# First 10 rows
print("First 10 rows:")
df[:10]

First 10 rows:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0
5,2021-01-11 00:00:00-05:00,210.02,210.45,208.35,209.08,23031300,0.0,0.0
6,2021-01-12 00:00:00-05:00,208.13,208.71,205.07,206.62,23249300,0.0,0.0
7,2021-01-13 00:00:00-05:00,205.75,208.38,205.66,207.98,20087100,0.0,0.0
8,2021-01-14 00:00:00-05:00,207.56,209.05,204.51,204.78,29480800,0.0,0.0
9,2021-01-15 00:00:00-05:00,205.26,206.22,203.83,204.43,31746500,0.0,0.0

In [33]:
df[-10:]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
994,2024-12-16 00:00:00-05:00,444.83,449.71,442.85,449.12,23598800,0.0,0.0
995,2024-12-17 00:00:00-05:00,448.55,452.80,447.11,451.98,22733500,0.0,0.0
996,2024-12-18 00:00:00-05:00,448.85,450.18,434.63,435.00,24444500,0.0,0.0
997,2024-12-19 00:00:00-05:00,439.21,440.76,433.94,434.64,22963700,0.0,0.0
998,2024-12-20 00:00:00-05:00,430.74,441.32,426.29,434.21,64263700,0.0,0.0
999,2024-12-23 00:00:00-05:00,434.35,435.26,430.46,432.87,19152500,0.0,0.0
1000,2024-12-24 00:00:00-05:00,432.27,437.20,431.82,436.93,7164500,0.0,0.0
1001,2024-12-26 00:00:00-05:00,436.68,438.53,434.24,435.72,8194200,0.0,0.0
1002,2024-12-27 00:00:00-05:00,432.22,432.84,424.02,428.18,18117700,0.0,0.0
1003,2024-12-30 00:00:00-05:00,423.73,425.21,419.59,422.51,13158700,0.0,0.0

In [23]:
# Last 10 rows
print("Last 10 rows:")
df[-10:]

Last 10 rows:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
994,2024-12-16 00:00:00-05:00,444.83,449.71,442.85,449.12,23598800,0.0,0.0
995,2024-12-17 00:00:00-05:00,448.55,452.80,447.11,451.98,22733500,0.0,0.0
996,2024-12-18 00:00:00-05:00,448.85,450.18,434.63,435.00,24444500,0.0,0.0
997,2024-12-19 00:00:00-05:00,439.21,440.76,433.94,434.64,22963700,0.0,0.0
998,2024-12-20 00:00:00-05:00,430.74,441.32,426.29,434.21,64263700,0.0,0.0
999,2024-12-23 00:00:00-05:00,434.35,435.26,430.46,432.87,19152500,0.0,0.0
1000,2024-12-24 00:00:00-05:00,432.27,437.20,431.82,436.93,7164500,0.0,0.0
1001,2024-12-26 00:00:00-05:00,436.68,438.53,434.24,435.72,8194200,0.0,0.0
1002,2024-12-27 00:00:00-05:00,432.22,432.84,424.02,428.18,18117700,0.0,0.0
1003,2024-12-30 00:00:00-05:00,423.73,425.21,419.59,422.51,13158700,0.0,0.0

In [34]:
df[30:41]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
30,2021-02-17 00:00:00-05:00,232.52,235.40,232.16,235.30,21653500,0.56,0.0
31,2021-02-18 00:00:00-05:00,232.99,235.04,232.08,234.90,16925600,0.00,0.0
32,2021-02-19 00:00:00-05:00,234.87,234.97,231.43,232.19,25262600,0.00,0.0
33,2021-02-22 00:00:00-05:00,228.77,229.26,223.93,225.96,36446900,0.00,0.0
34,2021-02-23 00:00:00-05:00,221.93,226.27,220.39,224.77,30228700,0.00,0.0
35,2021-02-24 00:00:00-05:00,221.63,226.63,220.65,226.00,26339700,0.00,0.0
36,2021-02-25 00:00:00-05:00,223.62,226.04,219.57,220.64,39542200,0.00,0.0
37,2021-02-26 00:00:00-05:00,223.09,226.79,221.17,223.91,37819200,0.00,0.0
38,2021-03-01 00:00:00-05:00,227.30,228.81,224.65,228.30,25324000,0.00,0.0
39,2021-03-02 00:00:00-05:00,228.37,228.65,224.94,225.35,22812500,0.00,0.0
40,2021-03-03 00:00:00-05:00,223.70,225.07,218.98,219.27,34029500,0.00,0.0

In [33]:
# Rows 100 to 110
print("Rows 100-110:")
df[100:110]

Rows 100-110:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
100,2021-05-27 00:00:00-04:00,242.57,242.87,240.72,240.78,24426200,0.0,0.0
101,2021-05-28 00:00:00-04:00,242.41,243.45,241.02,241.13,18270200,0.0,0.0
102,2021-06-01 00:00:00-04:00,242.63,242.69,238.51,238.93,23213300,0.0,0.0
103,2021-06-02 00:00:00-04:00,239.64,240.74,237.43,238.84,19406700,0.0,0.0
104,2021-06-03 00:00:00-04:00,236.83,237.91,234.68,237.30,25307700,0.0,0.0
105,2021-06-04 00:00:00-04:00,239.28,243.04,239.04,242.21,25281100,0.0,0.0
106,2021-06-07 00:00:00-04:00,241.42,245.39,241.26,245.12,23079200,0.0,0.0
107,2021-06-08 00:00:00-04:00,246.43,247.25,243.87,243.93,22455000,0.0,0.0
108,2021-06-09 00:00:00-04:00,245.12,246.78,244.54,244.91,17937600,0.0,0.0
109,2021-06-10 00:00:00-04:00,245.59,248.65,244.99,248.44,24563600,0.0,0.0

In [36]:
df[::5]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
5,2021-01-11 00:00:00-05:00,210.02,210.45,208.35,209.08,23031300,0.0,0.0
10,2021-01-19 00:00:00-05:00,205.49,208.59,204.41,208.07,30480900,0.0,0.0
15,2021-01-26 00:00:00-05:00,222.90,225.13,221.18,223.35,49169600,0.0,0.0
20,2021-02-02 00:00:00-05:00,231.97,232.94,229.46,230.25,25916300,0.0,0.0
...,...,...,...,...,...,...,...,...
980,2024-11-25 00:00:00-05:00,416.09,418.78,412.58,416.50,27691100,0.0,0.0
985,2024-12-03 00:00:00-05:00,427.49,430.11,425.40,428.84,18302000,0.0,0.0
990,2024-12-10 00:00:00-05:00,441.96,447.16,439.19,440.91,18469500,0.0,0.0
995,2024-12-17 00:00:00-05:00,448.55,452.80,447.11,451.98,22733500,0.0,0.0
1000,2024-12-24 00:00:00-05:00,432.27,437.20,431.82,436.93,7164500,0.0,0.0

In [25]:
# Every 50th row
print("Every 50th row:")
# df[::50]

Every 50th row:

## 6.2 Conditional Selection (Boolean Indexing)

In [49]:
df[(df["Volume"] > 40_000_000) | (df["High"] > 250)]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
15,2021-01-26 00:00:00-05:00,222.90,225.13,221.18,223.35,49169600,0.0,0.0
16,2021-01-27 00:00:00-05:00,228.80,231.14,221.24,223.90,69870600,0.0,0.0
17,2021-01-28 00:00:00-05:00,226.50,233.26,226.00,229.69,49111200,0.0,0.0
18,2021-01-29 00:00:00-05:00,226.87,228.82,222.41,222.99,42503100,0.0,0.0
41,2021-03-04 00:00:00-05:00,218.48,224.02,216.09,218.47,44727800,0.0,0.0
...,...,...,...,...,...,...,...,...
999,2024-12-23 00:00:00-05:00,434.35,435.26,430.46,432.87,19152500,0.0,0.0
1000,2024-12-24 00:00:00-05:00,432.27,437.20,431.82,436.93,7164500,0.0,0.0
1001,2024-12-26 00:00:00-05:00,436.68,438.53,434.24,435.72,8194200,0.0,0.0
1002,2024-12-27 00:00:00-05:00,432.22,432.84,424.02,428.18,18117700,0.0,0.0
1003,2024-12-30 00:00:00-05:00,423.73,425.21,419.59,422.51,13158700,0.0,0.0

In [37]:
# Days where closing price was above $300
high_price_days = df[df['Close'] > 300]

print(f"Number of days with Close > $300: {len(high_price_days)}")
print(f"Percentage of total days: {len(high_price_days) / len(df) * 100:.2f}%")
print("\nFirst few high-price days:")
high_price_days.head()

Number of days with Close > $300: 483
Percentage of total days: 48.11%

First few high-price days:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
202,2021-10-21 00:00:00-04:00,297.22,300.95,296.44,300.70,16918100,0.0,0.0
205,2021-10-26 00:00:00-04:00,300.93,302.29,298.61,300.07,28107300,0.0,0.0
206,2021-10-27 00:00:00-04:00,305.77,315.54,305.77,312.71,52588700,0.0,0.0
207,2021-10-28 00:00:00-04:00,313.83,314.35,310.96,313.85,26297900,0.0,0.0
208,2021-10-29 00:00:00-04:00,313.64,321.25,313.41,320.88,34766000,0.0,0.0

In [38]:
# Days with high volume (above 30 million)
high_volume_days = df[df['Volume'] > 30_000_000]

print(f"Number of high-volume days: {len(high_volume_days)}")
high_volume_days.head()

Number of high-volume days: 259

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
9,2021-01-15 00:00:00-05:00,205.26,206.22,203.83,204.43,31746500,0.0,0.0
10,2021-01-19 00:00:00-05:00,205.49,208.59,204.41,208.07,30480900,0.0,0.0
11,2021-01-20 00:00:00-05:00,209.28,217.06,208.89,215.67,37777300,0.0,0.0

In [41]:
# Multiple conditions with & (AND)
# Days where Close > $300 AND Volume > 30 million
condition = (df['Close'] > 340) & (df['Volume'] > 30_000_000)
filtered_df = df[condition]

print(f"Days with Close > $300 AND Volume > 30M: {len(filtered_df)}")
filtered_df.head()

Days with Close > $300 AND Volume > 30M: 31

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
616,2023-06-15 00:00:00-04:00,331.77,343.92,331.49,342.21,38899100,0.0,0.0
637,2023-07-18 00:00:00-04:00,339.98,360.57,336.38,353.40,64738600,0.0,0.0
638,2023-07-19 00:00:00-04:00,355.63,356.32,346.47,349.07,39732900,0.0,0.0
639,2023-07-20 00:00:00-04:00,347.58,351.91,339.52,341.00,33778400,0.0,0.0
642,2023-07-25 00:00:00-04:00,341.23,345.93,339.23,345.04,41637700,0.0,0.0

In [26]:
# Multiple conditions with | (OR)
# Days where Close > $350 OR Volume > 50 million
condition = (df['Close'] > 350) | (df['Volume'] > 50_000_000)
filtered_df = df[condition]

print(f"Days with Close > $350 OR Volume > 50M: {len(filtered_df)}")
filtered_df.head()

Days with Close > $350 OR Volume > 50M: 312

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
16,2021-01-27 00:00:00-05:00,228.80,231.14,221.24,223.90,69870600,0.0,0.0
206,2021-10-27 00:00:00-04:00,305.77,315.54,305.77,312.71,52588700,0.0,0.0
265,2022-01-21 00:00:00-05:00,293.43,294.80,286.56,286.97,57984400,0.0,0.0
266,2022-01-24 00:00:00-05:00,283.26,288.02,267.60,287.30,85731500,0.0,0.0
267,2022-01-25 00:00:00-05:00,282.60,285.96,276.44,279.66,72848600,0.0,0.0

In [51]:
type(df['High'])

pandas.core.series.Series

In [50]:
df[df['High'].between(350, 400)]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
637,2023-07-18 00:00:00-04:00,339.98,360.57,336.38,353.40,64738600,0.0,0.0
638,2023-07-19 00:00:00-04:00,355.63,356.32,346.47,349.07,39732900,0.0,0.0
639,2023-07-20 00:00:00-04:00,347.58,351.91,339.52,341.00,33778400,0.0,0.0
715,2023-11-06 00:00:00-05:00,348.20,352.23,348.10,351.24,23828300,0.0,0.0
716,2023-11-07 00:00:00-05:00,354.06,357.08,352.32,355.18,25833900,0.0,0.0
...,...,...,...,...,...,...,...,...
832,2024-04-25 00:00:00-04:00,389.69,395.48,383.75,394.64,40586500,0.0,0.0
835,2024-04-30 00:00:00-04:00,397.07,397.73,384.88,385.04,28781400,0.0,0.0
836,2024-05-01 00:00:00-04:00,388.28,397.29,386.01,390.59,23562500,0.0,0.0
837,2024-05-02 00:00:00-04:00,393.28,395.52,390.30,393.46,17709400,0.0,0.0
901,2024-08-05 00:00:00-04:00,385.58,397.34,382.02,391.50,40709200,0.0,0.0

In [27]:
# Using .between() for range selection
# Days where closing price was between $250 and $300
mid_range_days = df[df['High'].between(250, 300)]

print(f"Days with Close between $250-$300: {len(mid_range_days)}")
mid_range_days.head()

Days with Close between $250-$300: 298

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
70,2021-04-15 00:00:00-04:00,248.53,250.46,248.34,250.04,25627500,0.0,0.0
71,2021-04-16 00:00:00-04:00,250.01,251.49,248.21,251.24,24878600,0.0,0.0
72,2021-04-19 00:00:00-04:00,250.71,251.95,248.42,249.31,23209300,0.0,0.0
73,2021-04-20 00:00:00-04:00,248.42,250.72,247.48,248.85,19722900,0.0,0.0
74,2021-04-21 00:00:00-04:00,249.50,251.18,247.87,251.08,24030400,0.0,0.0

# 7. Indexing with iloc

In [55]:
df[:5]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0

In [59]:
df.iloc[5:11, 3:5]

       Low   Close
5   208.35  209.08
6   205.07  206.62
7   205.66  207.98
8   204.51  204.78
9   203.83  204.43
10  204.41  208.07

In [56]:
df.iloc[0:5, :2]

                        Date    Open
0  2021-01-04 00:00:00-05:00  213.93
1  2021-01-05 00:00:00-05:00  208.86
2  2021-01-06 00:00:00-05:00  203.97
3  2021-01-07 00:00:00-05:00  205.76
4  2021-01-08 00:00:00-05:00  210.22

In [38]:
# Select single row by position (row 0)
print("First row using iloc:")
df.iloc[0]

First row using iloc:

Date            2021-01-04 00:00:00-05:00
Open                               213.93
High                               214.38
Low                                 206.5
Close                              209.27
Volume                           37130100
Dividends                             0.0
Stock Splits                          0.0
Name: 0, dtype: object

In [ ]:
# Select single cell by position (row 0, column 4 = Close)
print("First closing price:")
first_close = df.iloc[0, 4]
print(f"${first_close:.2f}")

In [39]:
# Select multiple rows by position
print("Rows 0-4 using iloc:")
df.iloc[0:5]

Rows 0-4 using iloc:

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0

In [40]:
# Select specific rows and columns
# Rows 0-9, columns 0 (Date) and 4 (Close)
print("First 10 dates and closing prices:")
df.iloc[0:10, [0, 4]]

First 10 dates and closing prices:

                        Date   Close
0  2021-01-04 00:00:00-05:00  209.27
1  2021-01-05 00:00:00-05:00  209.48
2  2021-01-06 00:00:00-05:00  204.04
3  2021-01-07 00:00:00-05:00  209.85
4  2021-01-08 00:00:00-05:00  211.13
5  2021-01-11 00:00:00-05:00  209.08
6  2021-01-12 00:00:00-05:00  206.62
7  2021-01-13 00:00:00-05:00  207.98
8  2021-01-14 00:00:00-05:00  204.78
9  2021-01-15 00:00:00-05:00  204.43

In [41]:
# Select all rows, specific columns
# All rows, columns 1-4 (Open, High, Low, Close)
print("All OHLC data:")
df.iloc[:, 1:5].head()

All OHLC data:

     Open    High     Low   Close
0  213.93  214.38  206.50  209.27
1  208.86  210.07  207.36  209.48
2  203.97  208.12  203.75  204.04
3  205.76  210.86  205.45  209.85
4  210.22  212.05  208.64  211.13

In [42]:
# Select last row
print("Last trading day:")
df.iloc[-1]

Last trading day:

Date            2024-12-30 00:00:00-05:00
Open                               423.73
High                               425.21
Low                                419.59
Close                              422.51
Volume                           13158700
Dividends                             0.0
Stock Splits                          0.0
Name: 1003, dtype: object

# 8. Data Transformations - Create new Columns

In [43]:
df.head(1)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.5,209.27,37130100,0.0,0.0

In [60]:
df_transform = df.copy()

In [63]:
214.38 - 206.50

7.8799999999999955

In [62]:
df_transform.head(2)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0

In [69]:
df_transform["Volume"] = df_transform["High"] - df_transform["Low"]

In [70]:
df_transform.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily_Range,asdaskdalsdasklasdkls,Volumne
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,7.87,0.0,0.0,7.87,7.87,7.87
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,2.71,0.0,0.0,2.71,2.71,2.71
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,4.37,0.0,0.0,4.37,4.37,4.37
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,5.41,0.0,0.0,5.41,5.41,5.41
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,3.41,0.0,0.0,3.41,3.41,3.41

In [45]:
# Create a copy to work with
df_transform = df.copy()

# Daily price range
df_transform['Daily_Range'] = df_transform['High'] - df_transform['Low']

# # Daily range as percentage
df_transform['Range_Pct'] = (df_transform['Daily_Range'] / df_transform['Open']) * 100

# # Price change from open to close
df_transform['Price_Change'] = df_transform['Close'] - df_transform['Open']

# print("New columns created:")
# df_transform[['Date', 'Open', 'High', 'Low', 'Close', 'Daily_Range', 'Range_Pct', 'Price_Change']].head(10)

In [46]:
df_transform.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily_Range,Range_Pct,Price_Change
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0,7.87,3.68,-4.65
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0,2.71,1.30,0.62
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0,4.37,2.14,0.08
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0,5.41,2.63,4.09
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0,3.41,1.62,0.90

# 9. Grouping and Aggregation - Group By Year

In [47]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-01-04 00:00:00-05:00,213.93,214.38,206.50,209.27,37130100,0.0,0.0
1,2021-01-05 00:00:00-05:00,208.86,210.07,207.36,209.48,23823000,0.0,0.0
2,2021-01-06 00:00:00-05:00,203.97,208.12,203.75,204.04,35930700,0.0,0.0
3,2021-01-07 00:00:00-05:00,205.76,210.86,205.45,209.85,27694500,0.0,0.0
4,2021-01-08 00:00:00-05:00,210.22,212.05,208.64,211.13,22956200,0.0,0.0

In [78]:
df_transform[["Date", "Year", "Quarter"]].head()

                       Date  Year  Quarter
0 2021-01-04 05:00:00+00:00  2021        1
1 2021-01-05 05:00:00+00:00  2021        1
2 2021-01-06 05:00:00+00:00  2021        1
3 2021-01-07 05:00:00+00:00  2021        1
4 2021-01-08 05:00:00+00:00  2021        1

In [80]:
df_transform.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily_Range,asdaskdalsdasklasdkls,Volumne,Year,Quarter
0,2021-01-04 05:00:00+00:00,213.93,214.38,206.50,209.27,7.87,0.0,0.0,7.87,7.87,7.87,2021,1
1,2021-01-05 05:00:00+00:00,208.86,210.07,207.36,209.48,2.71,0.0,0.0,2.71,2.71,2.71,2021,1
2,2021-01-06 05:00:00+00:00,203.97,208.12,203.75,204.04,4.37,0.0,0.0,4.37,4.37,4.37,2021,1
3,2021-01-07 05:00:00+00:00,205.76,210.86,205.45,209.85,5.41,0.0,0.0,5.41,5.41,5.41,2021,1
4,2021-01-08 05:00:00+00:00,210.22,212.05,208.64,211.13,3.41,0.0,0.0,3.41,3.41,3.41,2021,1

In [83]:
df_transform[["Year","Quarter", "Close"]].groupby(["Year", "Quarter"]).agg(
    avg_close=('Close','mean'),
    max_close=('Close', 'max')
)

              avg_close  max_close
Year Quarter
2021 1           223.31     235.52
     2           245.19     262.11
     3           281.26     295.34
     4           314.00     332.61
2022 1           291.94     324.50
     2           263.93     305.96
     3           257.36     285.74
     4           234.49     251.68
2023 1           249.92     282.80
     2           307.79     342.21
     3           325.19     353.40
     4           351.01     377.78
2024 1           400.00     424.64
     2           418.05     448.67
     3           423.89     463.24
     4           423.20     451.98

In [74]:
df_transform['Date'] = pd.to_datetime(df_transform['Date'], utc=True)
df_transform['Year'] = df_transform['Date'].dt.year
df_transform['Quarter'] = df_transform['Date'].dt.quarter

In [53]:
df_transform[['Year','Quarter', 'Close']].groupby(['Year','Quarter']).agg(
    max_close=('Close', 'max'),
    avg_close=('Close', 'mean')
)

              max_close  avg_close
Year Quarter
2021 1           235.52     223.31
     2           262.11     245.19
     3           295.34     281.26
     4           332.61     314.00
2022 1           324.50     291.94
     2           305.96     263.93
     3           285.74     257.36
     4           251.68     234.49
2023 1           282.80     249.92
     2           342.21     307.79
     3           353.40     325.19
     4           377.78     351.01
2024 1           424.64     400.00
     2           448.67     418.05
     3           463.24     423.89
     4           451.98     423.20

In [58]:
yearly_stats = df_transform.groupby('Year')['Close'].agg([
    ('Mean', 'mean'),
    ('Median', 'median'),
    ('Min', 'min'),
    ('Max', 'max'),
    ('Std', 'std')
]).round(2)

print("Yearly statistics for closing prices:")
yearly_stats

Yearly statistics for closing prices:

        Mean  Median     Min     Max    Std
Year
2021  266.53  267.68  204.04  332.61  36.31
2022  261.78  258.90  209.05  324.50  24.47
2023  308.72  319.32  217.53  377.78  40.99
2024  416.45  415.15  363.03  463.24  18.10