# Introduction to YFINANCE
---

### What is yfinance?

**yfinance** is a Python library that provides easy access to financial data from Yahoo Finance. It allows you to download historical market data, real-time stock prices, and financial information for stocks, cryptocurrencies, currencies, and more.

**Important Disclaimer:**

*yfinance is not affiliated, endorsed, or vetted by Yahoo, Inc. It's an open-source tool that uses Yahoo's publicly available APIs, and is intended for research and educational purposes. You should refer to Yahoo!'s terms of use for details on your rights to use the actual data downloaded.*

### Installation

```bash
uv add yfinance
```

In [2]:
# Import required libraries
import yfinance as yf
import pandas as pd
import plotly as pl
# Display settings for better readability
pd.set_option('display.max_colum ns', None)
pd.set_option('display.width', None)

OptionError: No such keys(s): 'display.max_colum ns'

---

## 1. The Ticker Object

The **Ticker** object is the main interface for accessing data about a specific stock.

### Key Concept: What is a Ticker Symbol?

A **ticker symbol** is a unique abbreviation used to identify publicly traded companies on a stock exchange.

Examples:
- `AAPL` = Apple Inc.
- `MSFT` = Microsoft Corporation
- `GOOGL` = Alphabet Inc. (Google)
- `TSLA` = Tesla Inc.

In [4]:
# Create a Ticker object for Apple
apple = yf.Ticker("AAPL")

print("Ticker object created for Apple (AAPL)")
print(type(apple))

Ticker object created for Apple (AAPL)
<class 'yfinance.ticker.Ticker'>

In [5]:
# Get company info
info = apple.info

# Display selected information
print(f"Company Name: {info.get('longName', 'N/A')}")
print(f"Sector: {info.get('sector', 'N/A')}")
print(f"Industry: {info.get('industry', 'N/A')}")
print(f"Current Price: ${info.get('currentPrice', 'N/A')}")

Company Name: Apple Inc.
Sector: Technology
Industry: Consumer Electronics
Current Price: $277.55

---

## 2. Historical Data - The Most Important Function

The `.history()` method retrieves historical market data and returns it as a **pandas DataFrame**.

### Key Concept: DataFrame

A **DataFrame** is a 2-dimensional labeled data structure (like a table) from the pandas library. It has:
- **Rows**: indexed by dates (in our case)
- **Columns**: different data fields (Open, High, Low, Close, Volume, etc.)

### Key Concept: Time Periods

You can specify different time periods:
- `period`: Use predefined periods like `"1d"`, `"5d"`, `"1mo"`, `"3mo"`, `"6mo"`, `"1y"`, `"2y"`, `"5y"`, `"10y"`, `"ytd"`, `"max"`
- `start` and `end`: Use specific dates in format `"YYYY-MM-DD"`

In [6]:
# Get historical data for the last year
apple = yf.Ticker("AAPL")
data_1y = apple.history(period="1y")

print("Historical data for AAPL (last year):")
print(f"Data Frame: {type(data_1y)}")
print(data_1y.head())  # Show first 5 rows
print("\nDataFrame shape:", data_1y.shape)
print("Columns:", data_1y.columns.tolist())

Historical data for AAPL (last year):
Data Frame: <class 'pandas.core.frame.DataFrame'>
                                 Open        High         Low       Close  \
Date
2024-11-27 00:00:00-05:00  233.414318  234.628826  232.757286  233.872238
2024-11-29 00:00:00-05:00  233.752801  236.739294  232.916587  236.261459
2024-12-02 00:00:00-05:00  236.201715  239.705855  236.092209  238.511261
2024-12-03 00:00:00-05:00  238.730285  241.667000  237.824379  241.557495
2024-12-04 00:00:00-05:00  241.776494  243.010916  240.163793  241.915863

                             Volume  Dividends  Stock Splits
Date
2024-11-27 00:00:00-05:00  33498400        0.0           0.0
2024-11-29 00:00:00-05:00  28481400        0.0           0.0
2024-12-02 00:00:00-05:00  48137100        0.0           0.0
2024-12-03 00:00:00-05:00  38861000        0.0           0.0
2024-12-04 00:00:00-05:00  44383900        0.0           0.0

DataFrame shape: (250, 7)
Columns: ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits']

In [7]:
# Get historical data with specific start and end dates
data_custom = apple.history(start="2022-01-01", end="2024-12-31")

print(f"Historical data for AAPL from 2022-01-01 to 2024-12-31:")
print(f"Total trading days: {len(data_custom)}")
print("\nFirst 3 rows:")
print(data_custom.head(3))
print("\nLast 3 rows:")
print(data_custom.tail(3))

Historical data for AAPL from 2022-01-01 to 2024-12-31:
Total trading days: 752

First 3 rows:
                                 Open        High         Low       Close  \
Date
2022-01-03 00:00:00-05:00  174.176216  179.122459  174.058687  178.270325
2022-01-04 00:00:00-05:00  178.877573  179.181201  175.439682  176.007767
2022-01-05 00:00:00-05:00  175.919643  176.468135  171.051758  171.326004

                              Volume  Dividends  Stock Splits
Date
2022-01-03 00:00:00-05:00  104487900        0.0           0.0
2022-01-04 00:00:00-05:00   99310400        0.0           0.0
2022-01-05 00:00:00-05:00   94537600        0.0           0.0

Last 3 rows:
                                 Open        High         Low       Close  \
Date
2024-12-26 00:00:00-05:00  257.027541  258.928945  256.470064  257.853790
2024-12-27 00:00:00-05:00  256.669129  257.535238  251.920617  254.439224
2024-12-30 00:00:00-05:00  251.094347  252.358634  249.621015  251.064484

                             Volume  Dividends  Stock Splits
Date
2024-12-26 00:00:00-05:00  27237100        0.0           0.0
2024-12-27 00:00:00-05:00  42355300        0.0           0.0
2024-12-30 00:00:00-05:00  35557500        0.0           0.0

### Understanding the Columns

- **Open**: Opening price of the trading day
- **High**: Highest price during the trading day
- **Low**: Lowest price during the trading day
- **Close**: Closing price of the trading day (most commonly used)
- **Volume**: Number of shares traded
- **Dividends**: Dividend payments (if any)
- **Stock Splits**: Stock split information (if any)

In [14]:
# Accessing specific columns
closing_prices = data_1y['Close']

print("Closing prices (last 10 days):")
print(closing_prices.tail(10))

Closing prices (last 10 days):
Date
2025-11-11 00:00:00-05:00    275.250000
2025-11-12 00:00:00-05:00    273.470001
2025-11-13 00:00:00-05:00    272.950012
2025-11-14 00:00:00-05:00    272.410004
2025-11-17 00:00:00-05:00    267.459991
2025-11-18 00:00:00-05:00    267.440002
2025-11-19 00:00:00-05:00    268.559998
2025-11-20 00:00:00-05:00    266.250000
2025-11-21 00:00:00-05:00    271.489990
2025-11-24 00:00:00-05:00    273.479889
Name: Close, dtype: float64

---

## 3. Working with Multiple Stocks - The Tickers Class

In [8]:
data_multi = yf.download("AAPL", start="2022-01-01", end="2024-12-31")

C:\Users\fatih\AppData\Local\Temp\ipykernel_2320\740456583.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data_multi = yf.download("APPLE", start="2022-01-01", end="2024-12-31")
HTTP Error 404:
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['APPLE']: YFTzMissingError('possibly delisted; no timezone found')

In [26]:
# Download data for multiple stocks
tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "NVDA"]
data_multi = yf.download(tickers, start="2022-01-01", end="2024-12-31")

print("Multi-stock data structure:")
print(data_multi.head())
print("\nDataFrame shape:", data_multi.shape)

C:\Users\fatih\AppData\Local\Temp\ipykernel_15956\375307529.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data_multi = yf.download(tickers, start="2022-01-01", end="2024-12-31")
[*********************100%***********************]  6 of 6 completed

Multi-stock data structure:
Price            Close                                                 \
Ticker            AAPL        AMZN       GOOGL        MSFT       NVDA
Date
2022-01-03  178.270294  170.404495  143.998322  323.898376  30.064440
2022-01-04  176.007797  167.522003  143.410400  318.344421  29.235001
2022-01-05  171.326004  164.356995  136.831253  306.123871  27.552166
2022-01-06  168.465988  163.253998  136.803940  303.704895  28.125086
2022-01-07  168.632507  162.554001  136.078461  303.859741  27.195839

Price                         High                                      \
Ticker            TSLA        AAPL        AMZN       GOOGL        MSFT
Date
2022-01-03  399.926666  179.122429  170.703506  144.851931  327.043021
2022-01-04  383.196655  179.181232  171.399994  145.481610  324.333761
2022-01-05  362.706665  176.468135  167.126495  143.509694  315.499751
2022-01-06  354.899994  171.698187  164.800003  138.981426  308.368651
2022-01-07  342.320007  170.562032  165.243500  137.500158  306.239987

Price                                     Low                          \
Ticker           NVDA        TSLA        AAPL        AMZN       GOOGL
Date
2022-01-03  30.653332  400.356659  174.058657  166.160507  142.728576
2022-01-04  30.410788  402.666656  175.439712  166.349503  142.732080
2022-01-05  29.360764  390.113342  171.051758  164.356995  136.744859
2022-01-06  28.384598  362.666656  168.113384  161.936996  135.623089
2022-01-07  28.368634  360.309998  167.515931  162.031006  134.836523

Price                                                Open              \
Ticker            MSFT       NVDA        TSLA        AAPL        AMZN
Date
2022-01-03  319.089488  29.729070  378.679993  174.176186  167.550003
2022-01-04  315.548093  28.295768  374.350006  178.877604  170.438004
2022-01-05  305.736844  27.481300  360.336670  175.919643  166.882996
2022-01-06  301.392358  27.014177  340.166656  169.151603  163.450500
2022-01-07  300.037777  27.006195  336.666656  169.337715  163.839005

Price                                                         Volume  \
Ticker           GOOGL        MSFT       NVDA        TSLA       AAPL
Date
2022-01-03  144.061378  324.478932  29.759015  382.583344  104487900
2022-01-04  144.400065  323.975731  30.220147  396.516663   99310400
2022-01-05  143.430740  315.296537  28.894640  382.216675   94537600
2022-01-06  136.060077  302.998549  27.588096  359.000000   96904000
2022-01-07  137.199225  303.966161  28.088161  360.123322   86709100

Price
Ticker          AMZN     GOOGL      MSFT       NVDA       TSLA
Date
2022-01-03  63520000  28646000  28865100  391547000  103931400
2022-01-04  70726000  28400000  32674300  527154000  100248300
2022-01-05  64302000  54618000  40054300  498064000   80119800
2022-01-06  51958000  37348000  39646100  454186000   90336600
2022-01-07  46606000  29760000  32720000  409939000   84164700

DataFrame shape: (752, 30)

In [22]:
# Access closing prices for all stocks
closing_prices_multi = data_multi['Close']

print("Closing prices for all stocks:")
print(closing_prices_multi.head())
print("\nColumns:", closing_prices_multi.columns.tolist())

Closing prices for all stocks:
Ticker            AAPL        AMZN       GOOGL        MSFT       NVDA  \
Date
2022-01-03  178.270294  170.404495  143.998322  323.898376  30.064440
2022-01-04  176.007797  167.522003  143.410400  318.344421  29.235001
2022-01-05  171.326004  164.356995  136.831253  306.123871  27.552166
2022-01-06  168.465988  163.253998  136.803940  303.704895  28.125086
2022-01-07  168.632507  162.554001  136.078461  303.859741  27.195839

Ticker            TSLA
Date
2022-01-03  399.926666
2022-01-04  383.196655
2022-01-05  362.706665
2022-01-06  354.899994
2022-01-07  342.320007

Columns: ['AAPL', 'AMZN', 'GOOGL', 'MSFT', 'NVDA', 'TSLA']

---

## Summary: Most Important yfinance Functions

| Function | Purpose | Example |
|----------|---------|----------|
| `yf.Ticker(symbol)` | Create a ticker object | `apple = yf.Ticker("AAPL")` |
| `.history()` | Get historical data | `data = apple.history(period="1y")` |
| `.info` | Get company information | `info = apple.info` |
| `yf.download()` | Download multiple stocks | `data = yf.download(["AAPL", "MSFT"], start="2022-01-01")` |

---

## Practice Exercises

### Exercise 1: Calculate Annual Averages

**Task:** Download data for 6 stocks of your choice for the last 3 years (2022, 2023, 2024) and calculate the average closing price for each stock in each year.

**Steps:**
1. Select 6 stock tickers
2. Download historical data from 2022-01-01 to 2024-12-31
3. Calculate the average closing price for each year

**Hints:**
- Use `yf.download()` to get data for multiple stocks
- Use `.resample('Y')` or filter by year to group data
- Use `.mean()` to calculate averages

In [40]:
# Step 1: Define tickers
automobile_tickers = ["MBG.DE", "BMW.DE", "TSLA", "BYDDY"]

# Step 2: Download data
df_automobile = yf.download(automobile_tickers, start = "2022-01-01", end = "2025-11-01")

# Step 3: Calculate annual averages using groupby
df_automobile_aggregated = df_automobile.groupby(df_automobile.index.year)['Close'].mean().round(2)

# df_automobile_aggregated.plot(kind='bar', figsize=(12, 6))
df_automobile_aggregated

C:\Users\fatih\AppData\Local\Temp\ipykernel_2320\1181615481.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_automobile = yf.download(automobile_tickers, start = "2022-01-01", end = "2025-11-01")
[*********************100%***********************]  4 of 4 completed

Price   Close
Ticker BMW.DE  BYDDY MBG.DE    TSLA
Date
2022    64.50   9.79  47.75  263.09
2023    86.48   9.80  56.45  217.48
2024    82.59   9.74  56.35  230.61
2025    78.66  14.97  52.08  339.82

### Exercise 2: Best Performing Stock in 2024

**Task:** From the same 6 stocks, determine which stock had the highest return in 2024.

**Steps:**
1. Filter data for 2024 only
2. Calculate the return for each stock: `Return = (End Price - Start Price) / Start Price * 100`
3. Identify the stock with the highest return

**Hints:**
- use iloc!!!!!
- Consider using a dictionary or DataFrame to store results

In [45]:
df_automobile.head()

Price           Close                                         High             \
Ticker         BMW.DE      BYDDY     MBG.DE        TSLA     BMW.DE      BYDDY
Date
2022-01-03  69.899994  11.266516  50.267513  399.926666  70.221442  11.300456
2022-01-04  72.088913  11.185705  52.762600  383.196655  72.127177  11.361871
2022-01-05  73.657890  10.343667  54.877201  362.706665  73.772695  10.552157
2022-01-06  73.642586  10.304878  54.811352  354.899994  74.484477  10.350131
2022-01-07  73.168068  10.196593  53.823559  342.320007  73.879850  10.269322

Price                                    Low                        \
Ticker         MBG.DE        TSLA     BMW.DE      BYDDY     MBG.DE
Date
2022-01-03  50.626048  400.356659  67.917718  11.070957  49.674841
2022-01-04  53.143079  402.666656  69.792844  11.027318  50.787023
2022-01-05  54.913788  390.113342  71.897574  10.343667  52.974793
2022-01-06  55.923527  362.666656  72.410362  10.217603  53.808926
2022-01-07  55.374756  360.309998  72.724160  10.148107  53.684540

Price                        Open                                    \
Ticker            TSLA     BMW.DE      BYDDY     MBG.DE        TSLA
Date
2022-01-03  378.679993  68.047833  11.087118  50.121176  382.583344
2022-01-04  374.350006  70.328591  11.256817  50.838241  396.516663
2022-01-05  360.336670  72.326172  10.503671  52.974793  382.216675
2022-01-06  340.166656  72.479241  10.217603  54.094287  359.000000
2022-01-07  336.666656  73.474212  10.240231  54.906471  360.123322

Price          Volume
Ticker         BMW.DE      BYDDY     MBG.DE         TSLA
Date
2022-01-03   983398.0   829200.0  2654611.0  103931400.0
2022-01-04  1422271.0   953400.0  4936145.0  100248300.0
2022-01-05  1828361.0  1438200.0  5106683.0   80119800.0
2022-01-06  1229513.0   804000.0  3602804.0   90336600.0
2022-01-07  1193638.0   651600.0  2755179.0   84164700.0

In [ ]:
d

In [44]:
# Step 1: Filter data for 2024
df_automobile_2024 = df_automobile[df_automobile.index.year == 2024]["Close"]
df_automobile_2024
# Step 2: Calculate returns 

# Step 3: Identify best performing stock

Ticker         BMW.DE      BYDDY     MBG.DE        TSLA
Date
2024-01-02  90.937775   8.727735  54.071712  248.419998
2024-01-03  88.909592   8.851256  53.106907  238.449997
2024-01-04  90.240860   8.713108  53.209366  237.929993
2024-01-05  89.937088   8.674101  53.405739  237.490005
2024-01-08  90.419556   8.646471  54.268089  240.449997
...               ...        ...        ...         ...
2024-12-24        NaN  11.735790        NaN  462.279999
2024-12-26        NaN  11.725895        NaN  454.130005
2024-12-27  74.328781  11.552703  49.285042  431.660004
2024-12-30  74.936020  11.303638  49.515133  417.410004
2024-12-31        NaN  11.211267        NaN  403.839996

[259 rows x 4 columns]